import streamlit as st
import random
from fpdf import FPDF

# --- PAGE CONFIG ---
st.set_page_config(page_title="RealtorAI Pro Max", page_icon="🏠", layout="wide")

# --- CUSTOM STYLING ---
st.markdown("""
<style>
    /* Color ko White (#FFFFFF) kar diya taaki Dark Mode mein dikhe */
    .main-header {font-size:32px; font-weight:bold; color:#FFFFFF; margin-bottom: 20px;}
    .sub-header {font-size:18px; color:#E2E8F0;}
    .stButton>button {width: 100%; border-radius: 8px;}
</style>
""", unsafe_allow_html=True)

# --- SIDEBAR ---
with st.sidebar:
    st.title("RealtorAI 🚀")
    st.write("Generate premium property listings instantly.")
    st.info("💡 **Tip:** Add 'Servant Quarter' for luxury listings.")
    st.markdown("---")

# --- HEADER ---
st.markdown('<p class="main-header">🏢 Advanced Property Listing Generator</p>', unsafe_allow_html=True)
st.markdown("---")

# --- INPUT FORM (3 Columns for better look) ---
col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("### 🏠 Basic Info")
    property_type = st.selectbox("Property Type", ["House/Villa", "Apartment", "Penthouse", "Office Floor"])
    location = st.text_input("Location", value="Bahria Town, Lahore")
    price = st.text_input("Price", value="4.5 Crore")

with col2:
    st.markdown("### 🛋️ Layout & Rooms")
    bedrooms = st.slider("Bedrooms", 1, 10, 4)
    bathrooms = st.slider("Bathrooms", 1, 10, 5)
    # Naya Feature: Extra Rooms
    extra_rooms = st.multiselect("Extra Rooms", ["Drawing Room", "Dining Room", "TV Lounge", "Servant Quarter", "Study Room", "Store Room"])

with col3:
    st.markdown("### 🚗 Amenities")
    sq_ft = st.number_input("Area (Sq Ft)", 500, 20000, 3000)
    # Naya Feature: Parking & Furnishing
    parking = st.selectbox("Parking Space", ["No Parking", "1 Car Space", "2+ Car Spaces", "Garage"])
    furnishing = st.select_slider("Condition", options=["Unfurnished", "Semi-Furnished", "Fully Furnished"])

# Expandable Features Section (Taaki clean lage)
with st.expander("✨ Add Key Features (View, Security, etc.)"):
    features = st.text_area("Specific Highlights", 
                            "Corner Plot, Park Facing, Imported Fixtures, Jacuzzi, 24/7 Security")

tone = st.select_slider("🎭 Select Tone", options=["Standard", "Urgent", "Luxury", "Warm/Family"])

# --- LOGIC ENGINE (Advanced) ---
def generate_advanced_text():
    # 1. Opening Hook
    openings = {
        "Luxury": f"Step into a world of opulence with this meticulously designed {furnishing} {property_type} in {location}.",
        "Urgent": f"Hot Listing! Grab this amazing {property_type} in prime {location} before it's sold.",
        "Warm/Family": f"Looking for the perfect family home? This beautiful {property_type} in {location} is waiting for you.",
        "Standard": f"Available for sale: A spacious {property_type} located in the heart of {location}."
    }
    opening_line = openings.get(tone, openings["Standard"])

    # 2. Room & Layout Description
    # Extra rooms ko comma se join karein
    rooms_text = ""
    if extra_rooms:
        rooms_list = ", ".join(extra_rooms)
        rooms_text = f"It features a spacious layout including a separate {rooms_list}."
    
    layout_desc = (f"This {sq_ft} sq ft property boasts {bedrooms} master bedrooms with attached {bathrooms} modern bathrooms. "
                   f"{rooms_text}")

    # 3. Amenities & Parking Logic
    parking_text = f"Ample parking is available with a dedicated {parking}." if parking != "No Parking" else "Street parking is available."
    
    amenities_desc = (f"The unit comes {furnishing}, ensuring a hassle-free move. "
                      f"{parking_text} Key highlights include {features}.")

    # 4. Closing
    closing = f"Priced competitively at {price}. A must-see property!"

    # Combine everything
    full_text = f"{opening_line}\n\n{layout_desc}\n\n{amenities_desc}\n\n{closing}\n\n📞 Contact us to book a visit!"
    return full_text

# --- PDF FUNCTION (Safe from Errors) ---
def create_safe_pdf(text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="Property Listing Details", ln=True, align='C')
    pdf.ln(10)
    # Emoji remover fix
    clean_text = text.encode('latin-1', 'ignore').decode('latin-1')
    pdf.multi_cell(0, 10, txt=clean_text)
    pdf.ln(20)
    pdf.cell(200, 10, txt="Generated by RealtorAI", ln=True, align='C')
    return pdf.output(dest="S").encode("latin-1")

# --- ACTION AREA ---
if st.button("✨ Generate Advanced Listing", type="primary"):
    with st.spinner("Analyzing property details..."):
        result = generate_advanced_text()
        
        st.success("Description Generated Successfully!")
        st.text_area("Your Copy:", value=result, height=200)
        
        c1, c2 = st.columns(2)
        
        # PDF Button
        pdf_data = create_safe_pdf(result)
        with c1:
            st.download_button("📄 Download PDF", data=pdf_data, file_name="property_details.pdf", mime="application/pdf")
            
        # WhatsApp Button
        wa_url = f"https://wa.me/?text={result.replace(' ', '%20').replace('n', '%0A')}"
        with c2:
            st.link_button("📱 Share on WhatsApp", wa_url)

# Footer
st.markdown("---")
st.caption("RealtorAI v2.0 - Advanced Version")