import streamlit as st
import random
from fpdf import FPDF

# --- PAGE CONFIG ---
st.set_page_config(page_title="RealtorAI Pro Max", page_icon="🏠", layout="wide")

# --- CUSTOM STYLING (Dark Mode Friendly) ---
st.markdown("""
<style>
    .main-header {font-size:32px; font-weight:bold; color:#FFFFFF; margin-bottom: 20px;}
    .sub-header {font-size:18px; color:#E2E8F0;}
    .stButton>button {width: 100%; border-radius: 8px;}
</style>
""", unsafe_allow_html=True)

# --- SIDEBAR ---
with st.sidebar:
    st.title("RealtorAI 🚀")
    st.write("Generate premium property listings instantly.")
    st.markdown("---")
    st.write("Designed for Real Estate Agents.")

# --- HEADER ---
st.markdown('<p class="main-header">🏢 Advanced Property Listing Generator</p>', unsafe_allow_html=True)

# --- INPUT FORM ---
col1, col2, col3 = st.columns(3)

with col1:
    st.markdown("### 🏠 Basic Info")
    property_type = st.selectbox("Property Type", ["House/Villa", "Apartment", "Penthouse", "Office Floor"])
    location = st.text_input("Location", value="DHA Phase 6, Karachi")
    price = st.text_input("Price", value="4.5 Crore")

with col2:
    st.markdown("### 🛋️ Layout & Rooms")
    bedrooms = st.slider("Bedrooms", 1, 10, 4)
    bathrooms = st.slider("Bathrooms", 1, 10, 5)
    extra_rooms = st.multiselect("Extra Rooms", ["Drawing Room", "TV Lounge", "Servant Quarter", "Study Room"])

with col3:
    st.markdown("### 🚗 Amenities")
    sq_ft = st.number_input("Area (Sq Ft)", 500, 20000, 3000)
    parking = st.selectbox("Parking Space", ["No Parking", "1 Car Space", "2+ Car Spaces", "Garage"])
    furnishing = st.select_slider("Condition", options=["Unfurnished", "Semi-Furnished", "Fully Furnished"])

with st.expander("✨ Add Key Features"):
    features = st.text_area("Highlights", "Corner Plot, Park Facing, Imported Fixtures, Jacuzzi")

tone = st.select_slider("🎭 Select Tone", options=["Standard", "Urgent", "Luxury", "Warm/Family"])

# --- LOGIC ENGINE ---
def generate_advanced_text():
    openings = {
        "Luxury": f"Step into opulence with this {furnishing} {property_type} in {location}.",
        "Urgent": f"Hot Listing! Amazing {property_type} in {location} available now.",
        "Standard": f"For Sale: Spacious {property_type} located in {location}."
    }
    opening_line = openings.get(tone, openings["Standard"])
    
    rooms_text = ", ".join(extra_rooms) if extra_rooms else "spacious rooms"
    layout_desc = (f"This {sq_ft} sq ft property features {bedrooms} bedrooms, {bathrooms} bathrooms, and includes {rooms_text}.")
    
    parking_text = f"Includes {parking}." if parking != "No Parking" else ""
    amenities_desc = (f"The unit is {furnishing}. {parking_text} Highlights: {features}.")
    
    closing = f"Asking Price: {price}. Contact us for a visit!"
    
    return f"{opening_line}\n\n{layout_desc}\n\n{amenities_desc}\n\n{closing}"

# --- 🎨 NEW PROFESSIONAL PDF FUNCTION ---
def create_pro_pdf(text, details):
    pdf = FPDF()
    pdf.add_page()
    
    # 1. Page Border (Black Rectangle)
    pdf.rect(5, 5, 200, 287)
    
    # 2. Header Section
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(30, 58, 138) # Navy Blue Color
    pdf.cell(0, 20, "PROPERTY LISTING", align='C', ln=True)
    pdf.ln(5)
    
    # 3. Details Grid (Gray Boxes)
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(240, 240, 240) # Light Gray Background
    pdf.set_text_color(0, 0, 0) # Black Text
    
    # Row 1
    pdf.cell(95, 12, f" Location: {details['loc']}", border=1, fill=True)
    pdf.cell(95, 12, f" Price: {details['price']}", border=1, fill=True, ln=True)
    
    # Row 2
    pdf.cell(63, 12, f" Type: {details['type']}", border=1, fill=True)
    pdf.cell(63, 12, f" Area: {details['area']} sqft", border=1, fill=True)
    pdf.cell(64, 12, f" Beds/Baths: {details['bed']}/{details['bath']}", border=1, fill=True, ln=True)
    
    pdf.ln(10)
    
    # 4. Description Title
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(0, 10, "Property Description", ln=True)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y()) # Blue Line
    pdf.ln(5)
    
    # 5. Main Body Text
    pdf.set_font("Arial", '', 12)
    pdf.set_text_color(50, 50, 50)
    # Emoji fix
    clean_text = text.encode('latin-1', 'ignore').decode('latin-1')
    pdf.multi_cell(0, 8, clean_text)
    
    # 6. Footer
    pdf.set_y(-40)
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by RealtorAI Tool", align='C', ln=True)
    
    return pdf.output(dest="S").encode("latin-1")

# --- ACTION BUTTONS ---
if st.button("✨ Generate Listing", type="primary"):
    result = generate_advanced_text()
    
    st.success("Success!")
    st.text_area("Description:", value=result, height=200)
    
    # Details Dictionary for PDF
    prop_details = {
        "loc": location, "price": price, "type": property_type,
        "area": sq_ft, "bed": bedrooms, "bath": bathrooms
    }
    
    # Generate & Download
    pdf_data = create_pro_pdf(result, prop_details)
    st.download_button("📄 Download Professional PDF", data=pdf_data, file_name="Listing_Flyer.pdf", mime="application/pdf")